
spring:
  aop:
    proxy-target-class: true

  datasource:

    url: 主数据库url
    username: 用户名
    password: 密码

    driverClassName: com.mysql.cj.jdbc.Driver

    type: com.alibaba.druid.pool.DruidDataSource

    initialSize: 5
    minIdle: 5
    maxActive: 20

    maxWait: 60000

    timeBetweenEvictionRunsMillis: 60000

    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false

    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20

    filters: stat,wall,log4j

    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

    useGlobalDataSourceStat: true


  thymeleaf:
    cache: false

mybatis:
  configuration:
    map-underscore-to-camel-case: true
